---
- name: set timezone
  timezone: 
    name: "{{ ntp_timezone }}"

- name: config chrony daemon
  copy: 
    src: chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644

- name: chronyd service restarted
  service:
    name: chronyd
    state: restarted
    enabled: true
...