---
- name: install kerberos server packages
  yum:
    name: ['krb5-server','krb5-workstation']
    state: present

- name: copy config files
  copy:
    src: kdc.conf
    dest: /var/kerberos/krb5kdc/kdc.conf
    owner: root
    group: root
    mode: 0644
- name: copy config files
  copy:
    src: krb.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: copy config files
  copy:
    src: kadm.acl
    dest: /var/kerberos/krb5kdc/kadm5.acl
    owner: root
    group: root
    mode: 0644

- name: Create initial Kerberos database
  shell: kdb5_util -P {{ db_pass }} create -r {{ realm }} -s

- name: krb5kdc service enabled and started
  service:
    name: krb5kdc
    state: restarted
    enabled: true
    
- name: Create admin for administering Kerberos server
  shell: kadmin.local -q "addprinc -pw {{ kadmin_pass }} {{ kadmin_user }}"

- name: Create test user  Kerberos server
  shell: kadmin.local -q "addprinc -pw {{ kuser_pass }} {{ kuser_user }}"

- name: Create keytab for administering Kerberos server
  shell: kadmin.local -q "ktadd -k /var/kerberos/krb5kdc/kadm5.keytab kadmin/admin"
- name: Create keytab for administering Kerberos server
  shell: kadmin.local -q "ktadd -k /var/kerberos/krb5kdc/kadm5.keytab kadmin/changepw"

- name: kadmin service enabled and started
  service:
    name: kadmin
    state: restarted
    enabled: true

- name: create a principal for KDC server
  shell: kadmin.local -q "addprinc -randkey -kvno 3 {{ item }}"
  with_items:
   - host/ns.otus.test@OTUS.TEST
   - postgres/ns.otus.test@OTUS.TEST

- name: add all entires to keytab file on KDC server
  shell: kadmin.local -q "ktadd {{ item }}"
  with_items:
   - host/ns.otus.test
   - postgres/ns.otus.test
...